Make setup idempotent

diff --git a/setup b/setup
--- a/setup
+++ b/setup
@@ -3,9 +3,11 @@
 # Run this script from a location to which links should be added.
 # (eg, run it from $HOME)
 
-die() { echo $* >&2; exit 1; }
-test "$(pwd)" = "$HOME" || die "Run from $HOME"
-base=$(dirname $0)
+die() { echo "$@" >&2; exit 1; }
+warn() { test -z "$NOWARN" || echo "$@" >&2; }
+test "$(pwd)" = "$HOME" || warn "Running from $HOME"
+cd $HOME
+base=$( dirname $(realpath --relative-to=$HOME $0) )
 
 files='
 .bash-functions
@@ -23,4 +25,13 @@ files='
 .vimrc
 '
 
-for file in $files; do ln -s $base/$file . || die; done
+for file in $files; do
+	if test -e $file; then
+		if test "$(realpath $HOME/$file)" = "$(realpath $base/$file)"; then
+			die "aborting to avoid overwriting $file"
+		fi
+	fi
+done
+
+
+for file in $files; do ln -sf $base/$file . || die; done
