Suppress warning if BAD_WORDS -gt 1
Type: git

diff --git a/config/git/hooks/commit-msg b/config/git/hooks/commit-msg
--- a/config/git/hooks/commit-msg
+++ b/config/git/hooks/commit-msg
@@ -12,6 +12,8 @@
 
 . "$(dirname $0)"/common-hook-functions
 backup_name="$1"
+: ${WORD_FILE:=/usr/share/dict/words}
+: ${BAD_WORDS:=$BW}
 
 main() {
 	remove_comments "$@" || die
@@ -68,25 +70,26 @@ check_word() {
 	readtags "$word" 2> /dev/null | grep -q . && return 0;
 	get_words_from_git_log
 	printf '%s' "$word_list" | grep -qw "$word" && return 0
+	if ! test "$BAD_WORDS" -gt 1 2> /dev/null; then
+		warn "'$word' looks like a spelling error and/or typo"
+	fi
 	return 1
 }
 
 check_words() {
 	# Ensure that each word in $1 appears in the dictionary
-	: ${WORD_FILE:=/usr/share/dict/words}
 	if check_words_should_be_skipped; then return 0; fi
 	if ! < "$1" \
 		tr -cs '[:alpha:]_' '\n' | sort -u | {
 		status=0
 		while read word; do
 			if ! check_word "$word"; then
-				warn "'$word' looks like a spelling error and/or typo"
 				status=1
 			fi
 		done
 		test "$status" = 0
 	}; then
-		if test -z "$BAD_WORDS$BW"; then
+		if test -z "$BAD_WORDS"; then
 			warn "Set BAD_WORDS=1 (or BW) to allow, SKIP_SPELLCHECK=1 to skip"
 			return 1
 		fi
