Refactor g
Pull the check for raw out of the inner loop to save
a level of indentation.

Type: git

diff --git a/.bashd/git b/.bashd/git
--- a/.bashd/git
+++ b/.bashd/git
@@ -13,21 +13,19 @@ g() {
 
 	test $# = 0 && { set -- info; }
 
+	# replace numeric args with branch name
 	for arg; do
 		shift
 		orig=$arg
 
-		if test -z "$raw"; then
-			# replace numeric args with branch name
-			if test "$arg" = --; then raw=1; continue; fi
-			if test "$prev" != -n; then
-				arg=$(perl -e '
-					($s=shift) =~ s{(?<![~\w])(\d+)(?![~\w])|\{(\d+)\}}
-					{my $r=qx{git select-branch "$1$2"};
-					die "Cannot find branch" if $?; chomp $r; $r}ge;
-					print $s
-				' -- "$arg")
-			fi
+		if test -n "$raw" || test "$arg" = --; then raw=1; continue; fi
+		if test "$prev" != -n; then
+			arg=$(perl -e '
+				($s=shift) =~ s{(?<![~\w])(\d+)(?![~\w])|\{(\d+)\}}
+				{my $r=qx{git select-branch "$1$2"};
+				die "Cannot find branch" if $?; chomp $r; $r}ge;
+				print $s
+			' -- "$arg")
 		fi
 		test "$arg" != "$orig" && verbose=1
 		set -- "$@" "$arg"
