Do not treat ~ as a word boundary
We do not want a branch name replacement in a string like
HEAD~2

Type: git

diff --git a/.bashd/git b/.bashd/git
--- a/.bashd/git
+++ b/.bashd/git
@@ -28,8 +28,11 @@ g() {
 		(--    ) raw=1; continue;;
 		(*)
 			if test "$prev" != -n &&
-				! arg=$(echo "$arg" | perl -pe 's/(\b\d+\b)|\{(\d+)\}/my $r=qx{git select-branch "$1$2"};
-					die "Cannot find branch" if $?; chomp $r; $r/ge')
+				! arg=$(
+					echo "$arg" | perl -pe 's/(?<![~\w])(\d+)(?![~\w])|\{(\d+)\}/
+					my $r=qx{git select-branch "$1$2"};
+					die "Cannot find branch" if $?; chomp $r; $r/ge'
+				)
 			then
 				return 1
 			fi
