Be verbose when unable to decrypt secret
Type: sh

diff --git a/.bashd/secrets b/.bashd/secrets
--- a/.bashd/secrets
+++ b/.bashd/secrets
@@ -1,5 +1,10 @@
 
-for _secret in $HOME/.config/$USER/secrets/*.gpg; do
-	eval "export '$(basename "${_secret%.gpg}")'='$(gpg -qd "$_secret")'"
+for _file in $HOME/.config/$USER/secrets/*.gpg; do
+	_name=$(basename "${_file%.gpg}")
+	if ! _value=$(gpg -qd "$_file"); then
+		echo "gpg failure.  Unable to assign $_name" >&2
+	else
+		eval "export '$_name'='$_value'"
+	fi
 done
-unset _secret
+unset _file _name _value
