Do not load secrets when reloading from USR1
It is too annoying to have to type the password after a push.

Type: sh

diff --git a/.bashd/secrets b/.bashd/secrets
--- a/.bashd/secrets
+++ b/.bashd/secrets
@@ -1,10 +1,14 @@
 
-for _file in $HOME/.config/$USER/secrets/*.gpg; do
-	_name=$(basename "${_file%.gpg}")
-	if ! _value=$(gpg -qd "$_file"); then
-		echo "gpg failure.  Unable to assign $_name" >&2
-	else
-		eval "export '$_name'='$_value'"
-	fi
-done
-unset _file _name _value
+if test -n "$SKIP_SECRETS"; then
+	echo 'Not loading secrets (SKIP_SECRETS is set)' >&2
+else
+	for _file in $HOME/.config/$USER/secrets/*.gpg; do
+		_name=$(basename "${_file%.gpg}")
+		if ! _value=$(gpg -qd "$_file"); then
+			echo "gpg failure.  Unable to assign $_name" >&2
+		else
+			eval "export '$_name'='$_value'"
+		fi
+	done
+	unset _file _name _value
+fi
