Allow clearing of secrets
We should be able to clear the environment easily.  It would
be better if we did not rely on the names in ~/.config/secrets
for the list of items to clear, but this is good enough as I
expect that directory to be relatively stable.

Type: rc

diff --git a/.bashd/secrets b/.bashd/secrets
--- a/.bashd/secrets
+++ b/.bashd/secrets
@@ -1,18 +1,31 @@
 
-load_secrets() {
-	local _file _name _value
+_load_from_file() {
+	local _value
+	if ! _value=$(gpg -qd "$_file"); then
+		echo "gpg failure.  Unable to decrypt $_name" >&2
+	else
+		export "$_name"=$_value
+	fi
+}
+
+_load_secrets() {
+	local _file _name
 	for _file in $HOME/.config/secrets/*.gpg; do
 		_name=$(basename "${_file%.gpg}")
 		test "$_name" = '*' && continue
-		if ! _value=$(gpg -qd "$_file"); then
-			echo "gpg failure.  Unable to assign $_name" >&2
-		else
-			export "$_name"=$_value
-		fi
+		case $1 in
+		clear)
+			unset "$_name";;
+		*)
+			_load_from_file;;
+		esac
 	done
 }
+
 if test -n "$SKIP_SECRETS"; then
 	echo 'Not loading secrets (SKIP_SECRETS is set)' >&2
 else
-	load_secrets
+	_load_secrets "$1"
 fi
+
+unset _load_secrets _load_from_file
