Only query once for ignored files

diff --git a/.bashd/vi b/.bashd/vi
--- a/.bashd/vi
+++ b/.bashd/vi
@@ -1,18 +1,18 @@
 _check_if_ignored_by_git() {
+	local pause=no
 	for x; do
-		local pause=no
 		if git check-ignore -q "$x"; then
 			pause=yes
 			echo "WARNING: $x is ignored by git" >&2
 		fi
-		if test "$pause" = yes; then
-			echo "Press enter to continue, q<enter> to abort" >&2
-			read k
-			if test "$k" = q; then
-				return 1
-			fi
-		fi
 	done
+	if test "$pause" = yes; then
+		echo "Press enter to continue, q<enter> to abort" >&2
+		read k
+		if test "$k" = q; then
+			return 1
+		fi
+	fi
 }
 
 vi() {
