Handle errors cleanly when worktree does not exist
type: git

diff --git a/scripts/git-show-worktree b/scripts/git-show-worktree
--- a/scripts/git-show-worktree
+++ b/scripts/git-show-worktree
@@ -3,13 +3,19 @@
 # Given a branch as $1, print the full path of the work-tree
 # that houses it.  Fail if not such worktree exists.
 
+git rev-parse HEAD > /dev/null || exit
 if test $# -ne 1; then
 	echo 'Must give branch name as only argument' >&2
 	exit 1
 fi
-git rev-parse HEAD > /dev/null || exit
-branch=$1
 
 git worktree list --porcelain |
-awk '{gsub("refs/heads/", "")} $6 == branch {print $2; exit}' \
-	branch="$1" RS=
+dir=$(awk '{gsub("refs/heads/", "")} $6 == branch {print $2; exit}' \
+	branch="$1" RS=)
+
+if test -z "$dir"; then
+	echo "Cannot find worktree for branch $1" >&2
+	exit 1
+fi
+
+printf '%s' "$dir"
