Add main wrapper
Type: git

diff --git a/scripts/git-update b/scripts/git-update
--- a/scripts/git-update
+++ b/scripts/git-update
@@ -27,45 +27,48 @@ parse_args() {
 	done
 }
 
-parse_args "$@"
-shift $(($OPTIND-1))
+main() {
+	parse_args "$@"
+	shift $(($OPTIND-1))
 
-branch=${1-$(git base-branch)} || exit
-branch=${branch#refs/heads/}
+	branch=${1-$(git base-branch)} || exit
+	branch=${branch#refs/heads/}
 
-if ! git rev-parse --abbrev-ref $branch@{upstream} >/dev/null 2>&1; then
-	if test "$VERBOSITY" -gt 1; then
-		echo "No upstream info for $branch"
-	fi
-	exit 0
-fi
-
-old=$(git show-ref --verify --abbrev --hash refs/heads/$branch)
-
-if test -z "$old"; then
-	echo >&2 "Invalid branch: $branch.  Use 'git show-ref --heads' to see valid refs"
-	exit 1
-fi
-
-if ! test "$V" -ge 0 2> /dev/null; then
-	quiet=--quiet
-fi
-
-current=$(git rev-parse --abbrev-ref HEAD) || exit
-if test "$current" = "$branch"; then
-	git pull $quiet
-else
-	remote=$(git config branch.${branch}.remote)
-	upstream=$(git rev-parse --abbrev-ref --symbolic-full-name ${branch}@{u})
-	for name in remote upstream; do
-		if eval "test -z \"\$$name\""; then
-			echo "Can't find $name for $branch" >&2
-			exit 1
+	if ! git rev-parse --abbrev-ref $branch@{upstream} >/dev/null 2>&1; then
+		if test "$VERBOSITY" -gt 1; then
+			echo "No upstream info for $branch"
 		fi
-	done
-	git fetch $quiet "$remote" || exit 1
-	git update-ref refs/heads/$branch $upstream || exit 1
-fi
+		exit 0
+	fi
+
+	old=$(git show-ref --verify --abbrev --hash refs/heads/$branch)
+
+	if test -z "$old"; then
+		echo >&2 "Invalid branch: $branch.  Use 'git show-ref --heads' to see valid refs"
+		exit 1
+	fi
+
+	if ! test "$V" -ge 0 2> /dev/null; then
+		quiet=--quiet
+	fi
+
+	current=$(git rev-parse --abbrev-ref HEAD) || exit
+	if test "$current" = "$branch"; then
+		git pull $quiet
+	else
+		remote=$(git config branch.${branch}.remote)
+		upstream=$(git rev-parse --abbrev-ref --symbolic-full-name ${branch}@{u})
+		for name in remote upstream; do
+			if eval "test -z \"\$$name\""; then
+				echo "Can't find $name for $branch" >&2
+				exit 1
+			fi
+		done
+		git fetch $quiet "$remote" || exit 1
+		git update-ref refs/heads/$branch $upstream || exit 1
+	fi
+	print_summary
+}
 
 print_summary() {
 	if test "$VERBOSITY" -lt 1; then
@@ -88,4 +91,4 @@ print_summary() {
 	fi
 }
 
-print_summary
+main "$@"
