Prepend ERROR: to error messages written to tty
Type: git

diff --git a/scripts/git-recurse b/scripts/git-recurse
--- a/scripts/git-recurse
+++ b/scripts/git-recurse
@@ -16,7 +16,12 @@ if test "$1" = grep; then
 	fi
 fi
 
-header() { sed -e "s@^@${dir}${delim}@" -e 's@\./@@'; }
+unset err
+if test -t 1; then
+	err="$(tput sc; tput setaf 1)ERROR: $(tput rc; tput cuf 7)"
+fi
+
+header() { sed -e "s@^@$1${dir}${delim}@" -e 's@\./@@'; }
 
 # TODO (?) probably not worth the effort, but assuming that a directory is
 # the top-level of a repo merely because of the existence of .git is fragile.
@@ -25,7 +30,7 @@ header() { sed -e "s@^@${dir}${delim}@" -e 's@\./@@'; }
 # edge cases.  But this script does not need to be particularly robust.
 find . -type d -name .git | while read git_dir; do
 	dir="${git_dir%/.git}"
-	{ { git -C "$dir" "$@" 2>&3 | header >&4; } 3>&1 | header >&2; } 4>&1 &
+	{ { git -C "$dir" "$@" 2>&3 | header >&4; } 3>&1 | header "$err" >&2; } 4>&1 &
 	if ! wait $!; then RV=1; fi
 
 
