Specify remote vs upstream in error message
Rather than generically stating "remote", the error
message should be specific about what is missing.

type: git

diff --git a/scripts/git-update b/scripts/git-update
--- a/scripts/git-update
+++ b/scripts/git-update
@@ -31,10 +31,12 @@ if test "$current" = "$branch"; then
 else
 	remote=$(git config branch.${branch}.remote)
 	upstream=$(git rev-parse --abbrev-ref --symbolic-full-name ${branch}@{u})
-	if test -z "$remote" || test -z "$upstream"; then
-		echo "Can't find remote for $branch" >&2
-		exit 1
-	fi
+	for name in remote upstream; do
+		if eval "test -z \"\$$name\""; then
+			echo "Can't find $name for $branch" >&2
+			exit 1
+		fi
+	done
 	git fetch --quiet "$remote" || exit 1
 	git update-ref refs/heads/$branch $upstream || exit 1
 fi
