Ask to delete existing secret
Type: sh

diff --git a/scripts/make-secret b/scripts/make-secret
--- a/scripts/make-secret
+++ b/scripts/make-secret
@@ -4,7 +4,15 @@
 # in ~/.config/secrets
 
 name="$HOME/.config/secrets/${1?}.gpg"
-test -f "$name" && { echo "$name already exists!  Aborting" >&2; exit 1; }
+if test -f "$name"; then
+	printf "$name already exists!  Delete? (y/N): "
+	read yn < /dev/tty
+	case $yn in
+	y|Y|yes) rm $name;;
+	*) echo 'Aborting'; exit 1;;
+	esac
+fi
+
 
 if test -t 0; then pbpaste; else cat; fi | gpg -e -r "$EMAIL" > "$name"
 
