Check tmp1, not RESULTS
If no results were found, we aborted early and did not write RESULTS

diff --git a/scripts/search-bash-history b/scripts/search-bash-history
--- a/scripts/search-bash-history
+++ b/scripts/search-bash-history
@@ -77,13 +77,12 @@ check_tmux() {
 
 if test -z "$choice"; then
 	if test -z "$V"; then
-		printf "Only commands which did not fail are shown (set V to see all).  " >&2
+		printf "Only commands which did not fail are shown (set V to see all).\n" >&2
 	fi
-	if ! test -s $RESULTS; then
-		printf 'No results found.  ' >&2
+	if ! test -s $tmp1; then
+		printf "No results found for search terms: %s\n" "$*">&2
 		exit 1
 	fi
-	echo
 	< $RESULTS \
 	sed "${max_lines}q" \
 	| nl -s ') ' -w 2 -ba | expand | $tac \
