Allow specification of required trailers

diff --git a/git-templates/hooks/prepare-commit-msg b/git-templates/hooks/prepare-commit-msg
--- a/git-templates/hooks/prepare-commit-msg
+++ b/git-templates/hooks/prepare-commit-msg
@@ -13,7 +13,18 @@ main() {
 	if test -n "$ticket"; then
 		git-interpret-trailers --in-place --if-exists addIfDifferent --trailer ticket="$ticket" "$1"
 	fi
+	validate_trailers "$@"
 	run_local_hooks "$@"
+}
+
+# Ensure that all requested trailers are present
+validate_trailers() {
+	for value in $(git config --get-all core.required-trailers); do
+		if ! git interpret-trailers --parse "$1" |
+		awk '$1 == "'"$value"'" {print $2}' FS=': ' | grep -q .; then
+			die "Required trailer '$value' is missing"
+		fi
+	done
 }
 
 get_ticket_from_extant_message() {
