Report all missing trailers at once
Rather than just reporting one missing trailer, and then the
next on a subsequent run, accumulate a list of all missing
trailers and present them at once.  This is a better user
experience.

type: git

diff --git a/git-templates/hooks/prepare-commit-msg b/git-templates/hooks/prepare-commit-msg
--- a/git-templates/hooks/prepare-commit-msg
+++ b/git-templates/hooks/prepare-commit-msg
@@ -28,13 +28,16 @@ check_t_for_trailers() {
 
 # Ensure that all required trailers are present
 validate_trailers() {
+	local fail
 	local present_trailers=$(git interpret-trailers --parse "$1")
 	for value in $(git config --get-all commit.required-trailer); do
 		if ! echo "$present_trailers" |
 		awk '$1 == "'"$value"'" {print $2}' FS=': ' | grep -q .; then
-			die "Required trailer '$value' is missing"
+			fail=${fail:+$fail, }$value
+			echo "Required trailer '$value' is missing" >&2
 		fi
 	done
+	if test -n "$fail"; then die "Trailers missing: $fail"; fi
 }
 
 get_ticket_from_extant_message() {
